-- ============================================================================
-- Oracle Banking Database
-- Module       : 01_Database_Design / 02_Tables
-- Script       : 01_Create_Reference_Tables.sql
-- Purpose      : Create the reference and lookup tables used by the banking
--                schema
-- Execution    : Run as the BANKING_DB schema with F5 - Run Script
-- Dependencies : None
--
-- Design Notes
--   * Identity columns start from 1 for a clean deployment.
--   * NOT NULL rules and column defaults are defined with the tables.
--   * Primary keys, unique constraints, foreign keys, and named check
--     constraints are created later in 03_Constraints.
--   * Supporting indexes are created later in 04_Indexes.
--
-- Safety
--   DDL script. Run only in an empty target schema or during a controlled
--   rebuild.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SQLBLANKLINES ON

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT
PROMPT ================================================================================
PROMPT CREATE REFERENCE TABLES
PROMPT ================================================================================
PROMPT

PROMPT Creating COUNTRIES...

CREATE TABLE countries
(
    country_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    country_name  VARCHAR2(100) NOT NULL,
    country_code  CHAR(2)       NOT NULL
);

PROMPT Creating CITIES...

CREATE TABLE cities
(
    city_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    country_id    NUMBER        NOT NULL,
    city_name     VARCHAR2(100) NOT NULL
);

PROMPT Creating DISTRICTS...

CREATE TABLE districts
(
    district_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    city_id        NUMBER        NOT NULL,
    district_name  VARCHAR2(100) NOT NULL
);

PROMPT Creating SECTORS...

CREATE TABLE sectors
(
    sector_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    sector_name  VARCHAR2(50)                         NOT NULL,
    created_at   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR2(50)                        NOT NULL,
    updated_at   TIMESTAMP(6),
    updated_by   VARCHAR2(50)
);

PROMPT Creating CURRENCIES...

CREATE TABLE currencies
(
    currency_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    currency_code  CHAR(3)      NOT NULL,
    currency_name  VARCHAR2(50) NOT NULL,
    symbol         VARCHAR2(10)
);

PROMPT Creating ACCOUNT_TYPES...

CREATE TABLE account_types
(
    account_type_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    type_name        VARCHAR2(50)  NOT NULL,
    description      VARCHAR2(200)
);

PROMPT Creating CARD_TYPES...

CREATE TABLE card_types
(
    card_type_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    type_name     VARCHAR2(50)  NOT NULL,
    description   VARCHAR2(200)
);

PROMPT Creating CONTACT_TYPES...

CREATE TABLE contact_types
(
    contact_type_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    type_name        VARCHAR2(50)  NOT NULL,
    description      VARCHAR2(200)
);

PROMPT Creating TRANSACTION_CHANNELS...

CREATE TABLE transaction_channels
(
    channel_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    channel_name  VARCHAR2(50)  NOT NULL,
    description   VARCHAR2(200)
);

PROMPT Creating TRANSACTION_TYPES...

CREATE TABLE transaction_types
(
    transaction_type_id  NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    type_name            VARCHAR2(50)  NOT NULL,
    description          VARCHAR2(200)
);

PROMPT
PROMPT ================================================================================
PROMPT REFERENCE TABLE CREATION CHECK
PROMPT ================================================================================
PROMPT

COLUMN table_name FORMAT A30
COLUMN status     FORMAT A10

SELECT
    object_name AS table_name,
    status
FROM user_objects
WHERE object_type = 'TABLE'
  AND object_name IN
      (
          'COUNTRIES',
          'CITIES',
          'DISTRICTS',
          'SECTORS',
          'CURRENCIES',
          'ACCOUNT_TYPES',
          'CARD_TYPES',
          'CONTACT_TYPES',
          'TRANSACTION_CHANNELS',
          'TRANSACTION_TYPES'
      )
ORDER BY object_name;

PROMPT
PROMPT Reference table creation completed.
PROMPT Named constraints and supporting indexes are created by later modules.
PROMPT