-- ============================================================================
-- Oracle Banking Database
-- Module       : 01_Database_Design / 02_Tables
-- Script       : 02_Create_Customer_Tables.sql
-- Purpose      : Create customer, company, address, and contact tables
-- Execution    : Run as the BANKING_DB schema with F5 - Run Script
-- Dependencies : 01_Create_Reference_Tables.sql
--
-- Design Notes
--   * Identity columns start from 1 for a clean deployment.
--   * NOT NULL rules and column defaults are defined with the tables.
--   * Primary keys, unique constraints, foreign keys, and named check
--     constraints are created later in 03_Constraints.
--   * Supporting indexes are created later in 04_Indexes.
--
-- Safety
--   DDL script. Run only in an empty target schema or during a controlled
--   rebuild.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SQLBLANKLINES ON

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT
PROMPT ================================================================================
PROMPT CREATE CUSTOMER DOMAIN TABLES
PROMPT ================================================================================
PROMPT

PROMPT Creating COMPANIES...

CREATE TABLE companies
(
    company_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    company_name  VARCHAR2(200)                         NOT NULL,
    sector_id     NUMBER                                NOT NULL,
    city_id       NUMBER                                NOT NULL,
    tax_office    VARCHAR2(100)                         NOT NULL,
    status        VARCHAR2(20) DEFAULT 'ACTIVE'         NOT NULL,
    created_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR2(50)                          NOT NULL,
    updated_at    TIMESTAMP(6),
    updated_by    VARCHAR2(50)
);

PROMPT Creating CUSTOMERS...

CREATE TABLE customers
(
    customer_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    customer_no    VARCHAR2(20)                         NOT NULL,
    customer_type  CHAR(1)                              NOT NULL,
    status         VARCHAR2(20)                         NOT NULL,
    created_at     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     VARCHAR2(50)                         NOT NULL,
    updated_at     TIMESTAMP(6),
    updated_by     VARCHAR2(50)
);

PROMPT Creating INDIVIDUAL_CUSTOMERS...

CREATE TABLE individual_customers
(
    customer_id  NUMBER                              NOT NULL,
    first_name   VARCHAR2(50)                        NOT NULL,
    last_name    VARCHAR2(50)                        NOT NULL,
    national_id  CHAR(11)                            NOT NULL,
    birth_date   DATE,
    created_at   TIMESTAMP(6) DEFAULT SYSTIMESTAMP   NOT NULL,
    created_by   VARCHAR2(50) DEFAULT 'SYSTEM'       NOT NULL,
    updated_at   TIMESTAMP(6),
    updated_by   VARCHAR2(50)
);

PROMPT Creating CORPORATE_CUSTOMERS...

CREATE TABLE corporate_customers
(
    customer_id          NUMBER                            NOT NULL,
    company_id           NUMBER                            NOT NULL,
    tax_number           VARCHAR2(11)                      NOT NULL,
    registration_number  VARCHAR2(50)                      NOT NULL,
    created_at           TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by           VARCHAR2(50) DEFAULT 'SYSTEM'     NOT NULL,
    updated_at           TIMESTAMP(6),
    updated_by           VARCHAR2(50)
);

PROMPT Creating CUSTOMER_ADDRESSES...

CREATE TABLE customer_addresses
(
    address_id    NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    customer_id   NUMBER                            NOT NULL,
    district_id   NUMBER                            NOT NULL,
    address_line  VARCHAR2(250)                     NOT NULL,
    postal_code   VARCHAR2(10),
    address_type  VARCHAR2(20)                      NOT NULL,
    created_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    created_by    VARCHAR2(50) DEFAULT 'SYSTEM'     NOT NULL,
    updated_at    TIMESTAMP(6),
    updated_by    VARCHAR2(50)
);

PROMPT Creating CUSTOMER_CONTACTS...

CREATE TABLE customer_contacts
(
    contact_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    customer_id      NUMBER                            NOT NULL,
    contact_type_id  NUMBER                            NOT NULL,
    contact_value    VARCHAR2(100)                     NOT NULL,
    is_primary       CHAR(1) DEFAULT 'N'               NOT NULL,
    priority_rank    NUMBER DEFAULT 1,
    is_verified      CHAR(1) DEFAULT 'N'               NOT NULL,
    source_channel   VARCHAR2(20),
    created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at       TIMESTAMP(6),
    created_by       VARCHAR2(50) DEFAULT 'SYSTEM'     NOT NULL,
    updated_by       VARCHAR2(50)
);

PROMPT
PROMPT ================================================================================
PROMPT CUSTOMER DOMAIN TABLE CREATION CHECK
PROMPT ================================================================================
PROMPT

COLUMN table_name FORMAT A30
COLUMN status     FORMAT A10

SELECT
    object_name AS table_name,
    status
FROM user_objects
WHERE object_type = 'TABLE'
  AND object_name IN
      (
          'COMPANIES',
          'CUSTOMERS',
          'INDIVIDUAL_CUSTOMERS',
          'CORPORATE_CUSTOMERS',
          'CUSTOMER_ADDRESSES',
          'CUSTOMER_CONTACTS'
      )
ORDER BY object_name;

PROMPT
PROMPT Customer domain table creation completed.
PROMPT Named constraints and supporting indexes are created by later modules.
PROMPT