-- ============================================================================
-- Oracle Banking Database
-- Module       : 01_Database_Design / 02_Tables
-- Script       : 03_Create_Account_And_Card_Tables.sql
-- Purpose      : Create branch, account, beneficiary, card, and exchange-rate
--                tables
-- Execution    : Run as the BANKING_DB schema with F5 - Run Script
-- Dependencies : 01_Create_Reference_Tables.sql
--                02_Create_Customer_Tables.sql
--
-- Design Notes
--   * Identity columns start from 1 for a clean deployment.
--   * NOT NULL rules and column defaults are defined with the tables.
--   * Primary keys, unique constraints, foreign keys, and named check
--     constraints are created later in 03_Constraints.
--   * Supporting indexes are created later in 04_Indexes.
--
-- Safety
--   DDL script. Run only in an empty target schema or during a controlled
--   rebuild.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SQLBLANKLINES ON

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT
PROMPT ================================================================================
PROMPT CREATE ACCOUNT AND CARD DOMAIN TABLES
PROMPT ================================================================================
PROMPT

PROMPT Creating BRANCHES...

CREATE TABLE branches
(
    branch_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    branch_name   VARCHAR2(150)                  NOT NULL,
    branch_code   VARCHAR2(20)                   NOT NULL,
    city_id       NUMBER                         NOT NULL,
    phone         VARCHAR2(20),
    address       VARCHAR2(250),
    opening_date  DATE,
    status        VARCHAR2(20) DEFAULT 'ACTIVE'  NOT NULL,
    created_at    DATE DEFAULT SYSDATE           NOT NULL,
    created_by    VARCHAR2(128) DEFAULT USER     NOT NULL,
    updated_at    DATE,
    updated_by    VARCHAR2(128)
);

PROMPT Creating ACCOUNTS...

CREATE TABLE accounts
(
    account_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    customer_id      NUMBER                             NOT NULL,
    branch_id        NUMBER                             NOT NULL,
    account_type_id  NUMBER                             NOT NULL,
    currency_id      NUMBER                             NOT NULL,
    account_number   VARCHAR2(20)                       NOT NULL,
    iban             VARCHAR2(34)                       NOT NULL,
    balance          NUMBER(18,2) DEFAULT 0,
    status           VARCHAR2(20)                       NOT NULL,
    opening_date     DATE                               NOT NULL,
    closing_date     DATE,
    created_at       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR2(50),
    updated_at       TIMESTAMP(6),
    updated_by       VARCHAR2(50)
);

PROMPT Creating BENEFICIARIES...

CREATE TABLE beneficiaries
(
    beneficiary_id          NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    customer_id             NUMBER                            NOT NULL,
    beneficiary_account_id  NUMBER                            NOT NULL,
    nickname                VARCHAR2(100),
    created_at              TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by              VARCHAR2(50)                      NOT NULL,
    updated_at              TIMESTAMP(6),
    updated_by              VARCHAR2(50)
);

PROMPT Creating CARDS...

CREATE TABLE cards
(
    card_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    account_id    NUMBER                             NOT NULL,
    card_type_id  NUMBER                             NOT NULL,
    card_number   VARCHAR2(20)                       NOT NULL,
    expiry_date   DATE                               NOT NULL,
    status        VARCHAR2(20)                       NOT NULL,
    created_at    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR2(50),
    updated_at    TIMESTAMP(6),
    updated_by    VARCHAR2(50)
);

PROMPT Creating EXCHANGE_RATES...

CREATE TABLE exchange_rates
(
    rate_id           NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    currency_id       NUMBER                         NOT NULL,
    base_currency_id  NUMBER                         NOT NULL,
    buy_rate          NUMBER(18,6)                   NOT NULL,
    sell_rate         NUMBER(18,6)                   NOT NULL,
    rate_date         DATE                           NOT NULL,
    created_at        DATE DEFAULT SYSDATE           NOT NULL,
    created_by        VARCHAR2(128) DEFAULT USER     NOT NULL,
    updated_at        DATE,
    updated_by        VARCHAR2(128)
);

PROMPT
PROMPT ================================================================================
PROMPT ACCOUNT AND CARD DOMAIN TABLE CREATION CHECK
PROMPT ================================================================================
PROMPT

COLUMN table_name FORMAT A30
COLUMN status     FORMAT A10

SELECT
    object_name AS table_name,
    status
FROM user_objects
WHERE object_type = 'TABLE'
  AND object_name IN
      (
          'BRANCHES',
          'ACCOUNTS',
          'BENEFICIARIES',
          'CARDS',
          'EXCHANGE_RATES'
      )
ORDER BY object_name;

PROMPT
PROMPT Account and card domain table creation completed.
PROMPT Named constraints and supporting indexes are created by later modules.
PROMPT