-- ============================================================================
-- Oracle Banking Database
-- Module       : 01_Database_Design / 02_Tables
-- Script       : 04_Create_Transaction_And_Log_Tables.sql
-- Purpose      : Create transaction, transaction-history, audit, error, and
--                schema DDL audit tables
-- Execution    : Run as the BANKING_DB schema with F5 - Run Script
-- Dependencies : 01_Create_Reference_Tables.sql
--                02_Create_Customer_Tables.sql
--                03_Create_Account_And_Card_Tables.sql
--
-- Design Notes
--   * Identity columns start from 1 for a clean deployment.
--   * NOT NULL rules and column defaults are defined with the tables.
--   * Primary keys, unique constraints, foreign keys, and named check
--     constraints are created later in 03_Constraints.
--   * Supporting indexes are created later in 04_Indexes.
--
-- Safety
--   DDL script. Run only in an empty target schema or during a controlled
--   rebuild.
-- ============================================================================

SET DEFINE OFF
SET VERIFY OFF
SET FEEDBACK ON
SET SQLBLANKLINES ON

WHENEVER SQLERROR EXIT SQL.SQLCODE

PROMPT
PROMPT ================================================================================
PROMPT CREATE TRANSACTION AND LOG TABLES
PROMPT ================================================================================
PROMPT

PROMPT Creating TRANSACTIONS...

CREATE TABLE transactions
(
    transaction_id      NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    source_account_id   NUMBER                             NOT NULL,
    target_account_id   NUMBER,
    transaction_type_id NUMBER                             NOT NULL,
    channel_id          NUMBER                             NOT NULL,
    currency_id         NUMBER                             NOT NULL,
    amount              NUMBER(18,2)                       NOT NULL,
    transaction_date    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    description         VARCHAR2(250),
    reference_number    VARCHAR2(50)                       NOT NULL,
    status              VARCHAR2(20)                       NOT NULL
);

PROMPT Creating TRANSACTION_STATUS_HISTORY...

CREATE TABLE transaction_status_history
(
    history_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    transaction_id   NUMBER                            NOT NULL,
    old_status       VARCHAR2(20),
    new_status       VARCHAR2(20)                      NOT NULL,
    changed_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    changed_by       VARCHAR2(128) DEFAULT USER        NOT NULL,
    change_group_id  VARCHAR2(32)                      NOT NULL
);

PROMPT Creating AUDIT_LOGS...

CREATE TABLE audit_logs
(
    audit_log_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    logged_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    action_type        VARCHAR2(20)                       NOT NULL,
    entity_name        VARCHAR2(128)                      NOT NULL,
    entity_id          VARCHAR2(200),
    module_name        VARCHAR2(128),
    procedure_name     VARCHAR2(128),
    operation_name     VARCHAR2(200),
    old_data           CLOB,
    new_data           CLOB,
    context_data       CLOB,
    session_user       VARCHAR2(128)
        DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER')
        NOT NULL,
    client_identifier  VARCHAR2(256),
    host_name          VARCHAR2(256),
    os_user            VARCHAR2(128),
    session_id         NUMBER,
    transaction_id     VARCHAR2(100)
);

PROMPT Creating ERROR_LOGS...

CREATE TABLE error_logs
(
    error_log_id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    logged_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    severity           VARCHAR2(10) DEFAULT 'ERROR'      NOT NULL,
    error_code         NUMBER,
    error_message      VARCHAR2(4000),
    error_stack        CLOB,
    error_backtrace    CLOB,
    call_stack         CLOB,
    module_name        VARCHAR2(128),
    procedure_name     VARCHAR2(128),
    operation_name     VARCHAR2(200),
    entity_name        VARCHAR2(128),
    entity_id          VARCHAR2(200),
    context_data       CLOB,
    session_user       VARCHAR2(128)
        DEFAULT SYS_CONTEXT('USERENV', 'SESSION_USER')
        NOT NULL,
    client_identifier  VARCHAR2(256),
    host_name          VARCHAR2(256),
    os_user            VARCHAR2(128),
    session_id         NUMBER,
    transaction_id     VARCHAR2(100)
);

PROMPT Creating DDL_AUDIT_LOGS...

CREATE TABLE ddl_audit_logs
(
    ddl_audit_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1 INCREMENT BY 1 CACHE 20)
        NOT NULL,

    event_type       VARCHAR2(30)                       NOT NULL,
    object_owner     VARCHAR2(128),
    object_name      VARCHAR2(128),
    object_type      VARCHAR2(30),
    login_user       VARCHAR2(128)                      NOT NULL,
    session_user     VARCHAR2(128),
    current_schema   VARCHAR2(128),
    os_user          VARCHAR2(255),
    host_name        VARCHAR2(255),
    ip_address       VARCHAR2(64),
    module_name      VARCHAR2(255),
    event_timestamp  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    sql_text         CLOB
);

PROMPT
PROMPT ================================================================================
PROMPT TRANSACTION AND LOG TABLE CREATION CHECK
PROMPT ================================================================================
PROMPT

COLUMN table_name FORMAT A35
COLUMN status     FORMAT A10

SELECT
    object_name AS table_name,
    status
FROM user_objects
WHERE object_type = 'TABLE'
  AND object_name IN
      (
          'TRANSACTIONS',
          'TRANSACTION_STATUS_HISTORY',
          'AUDIT_LOGS',
          'ERROR_LOGS',
          'DDL_AUDIT_LOGS'
      )
ORDER BY object_name;

PROMPT
PROMPT Transaction and log table creation completed.
PROMPT Named constraints and supporting indexes are created by later modules.
PROMPT